# -*- coding: utf-8 -*-
"""Python-Notebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UBQv5m0gnxCoLUbxjeDGq5fWqgTmunzT
"""

numbers = [1,2,3]
new_list = []
for n in numbers:
  add_1 = n + 1
  new_list.append(add_1)

print(numbers)
print(new_list)

# using list comprehension
#new_list = [new_item for item in list]
numbers = [1,2,3]
new_list = [n+1 for n in numbers]
print(new_list)

name = "Amrit"
letters_list = [letter for letter in name]
print(letters_list)

# Python Sequence

# list
# range
# string
# tuple

range_list = [num*2 for num in range(1,5)]
print(range_list)

# Conditional List Comprehension
# new_list = [new_item for item in list if test]

names = ["Alex", "Beth", "Caroline", "Dave", "Elaner", "Freddie"]
names

short_names = [name for name in names if len(name) < 5]
print(short_names)

upperCase = [name.upper() for name in names if len(name) > 5]
print(upperCase)

