# -*- coding: utf-8 -*-
"""Python-Notebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UBQv5m0gnxCoLUbxjeDGq5fWqgTmunzT
"""

numbers = [1,2,3]
new_list = []
for n in numbers:
  add_1 = n + 1
  new_list.append(add_1)

print(numbers)
print(new_list)

# using list comprehension
#new_list = [new_item for item in list]
numbers = [1,2,3]
new_list = [n+1 for n in numbers]
print(new_list)

name = "Amrit"
letters_list = [letter for letter in name]
print(letters_list)

# Python Sequence

# list
# range
# string
# tuple

range_list = [num*2 for num in range(1,5)]
print(range_list)

# Conditional List Comprehension
# new_list = [new_item for item in list if test]

names = ["Alex", "Beth", "Caroline", "Dave", "Elaner", "Freddie"]
names

short_names = [name for name in names if len(name) < 5]
print(short_names)

upperCase = [name.upper() for name in names if len(name) > 5]
print(upperCase)

# Instructions - You are going to write a List Comprehension to create a
#new list called squared_numbers. This new list should contain every number
#in the list number in the list numbers but each number should be squared.

# e.g 4*4 = 16
# 4 squared equals to 16.

numbers = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
squared_numbers = [data**2 for data in numbers]
print(squared_numbers)

# Instructions
#  You are going to write a List Comprehension to create a new list called result. This new list should only
#  contain the even numbers from the list numbers.
# Example Output [2, 8, 34]
numbers = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
result = [data for data in numbers if data % 2 == 0]
print(result)

